<a href="https://colab.research.google.com/github/jfleon-dev/university-ai-labs/blob/main/clasificacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


# ════════════════════════════════════════════════════════════
# SECCIÓN 1: CLASIFICACIÓN
# ════════════════════════════════════════════════════════════

print("=" * 55)
print("  SECCIÓN 1 – CLASIFICACIÓN (KNeighborsClassifier)")
print("=" * 55)

# 1) Cargar Iris desde sklearn
iris = load_iris()

# 2-3) Separar X e y
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

print(f"\nDataset cargado: {X.shape[0]} muestras, {X.shape[1]} características")
print(f"Clases: {list(iris.target_names)}\n")

# 4) Dividir en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5) Crear y entrenar el clasificador KNN
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)

# 6) Evaluar el modelo
y_pred = knn_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Precisión: {accuracy}")
print("Matriz de confusión:")
print(cm)
print("\nInterpretación de la matriz de confusión:")
for i, nombre in enumerate(iris.target_names):
    correct = cm[i, i]
    total   = cm[i].sum()
    print(f"  {nombre:15s}: {correct}/{total} correctas")

# 7) Muestra nueva
test_sample = pd.DataFrame([[5.1, 3.5, 1.4, 0.2]], columns=iris.feature_names)
pred = knn_classifier.predict(test_sample)
print(f"\nMuestra nueva {test_sample.values[0]} → clase predicha: "
      f"{pred[0]} ({iris.target_names[pred[0]]})")


# ════════════════════════════════════════════════════════════
# SECCIÓN 2: REGRESIÓN
# ════════════════════════════════════════════════════════════

print("\n" + "=" * 55)
print("  SECCIÓN 2 – REGRESIÓN (KNeighborsRegressor)")
print("=" * 55)

# NOTA: load_boston fue eliminado en scikit-learn 1.2 por problemas éticos.
# Usamos el CSV de Iris para demostrar el mismo flujo de trabajo:
# Objetivo → predecir PetalLengthCm a partir de las otras 3 medidas.

df = pd.read_csv("Iris.csv")  # ajusta la ruta si es necesario

X_reg = df[["SepalLengthCm", "SepalWidthCm", "PetalWidthCm"]]
y_reg = df["PetalLengthCm"]

print(f"\nDataset: {df.shape[0]} muestras")
print("Variable objetivo: PetalLengthCm")
print(f"Variables predictoras: {list(X_reg.columns)}\n")

# Dividir
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Entrenar KNN Regresor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train_r, y_train_r)

# Evaluar
y_pred_r = knn_regressor.predict(X_test_r)
mse = mean_squared_error(y_test_r, y_pred_r)
r2  = r2_score(y_test_r, y_pred_r)

print(f"Error cuadrático medio (MSE): {mse:.4f}")
print(f"R-cuadrada (R²):             {r2:.4f}")

# Muestra nueva
sample_r = pd.DataFrame([[5.1, 3.5, 0.2]], columns=["SepalLengthCm", "SepalWidthCm", "PetalWidthCm"])
pred_val = knn_regressor.predict(sample_r)
print(f"\nMuestra nueva {sample_r.values[0]} → PetalLength predicho: {pred_val[0]:.2f} cm")


  SECCIÓN 1 – CLASIFICACIÓN (KNeighborsClassifier)

Dataset cargado: 150 muestras, 4 características
Clases: [np.str_('setosa'), np.str_('versicolor'), np.str_('virginica')]

Precisión: 1.0
Matriz de confusión:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Interpretación de la matriz de confusión:
  setosa         : 10/10 correctas
  versicolor     : 9/9 correctas
  virginica      : 11/11 correctas

Muestra nueva [5.1 3.5 1.4 0.2] → clase predicha: 0 (setosa)

  SECCIÓN 2 – REGRESIÓN (KNeighborsRegressor)

Dataset: 150 muestras
Variable objetivo: PetalLengthCm
Variables predictoras: ['SepalLengthCm', 'SepalWidthCm', 'PetalWidthCm']

Error cuadrático medio (MSE): 0.1032
R-cuadrada (R²):             0.9685

Muestra nueva [5.1 3.5 0.2] → PetalLength predicho: 1.42 cm
